# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zitadel < Formula
  desc "Open source identity solution built for the container and cloud era"
  homepage "https://zitadel.com"
  version "v3.2.3"
  license "Apache 2.0"

  depends_on "go" => :optional
  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zitadel/zitadel/releases/download/v3.2.3/zitadel-darwin-arm64.tar.gz"
      sha256 "9ca08f9a1896ce6fcc88940739722f4468738ab21e754fa1ad646ba57c8ec80c"

      def install
        bin.install "zitadel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zitadel/zitadel/releases/download/v3.2.3/zitadel-darwin-amd64.tar.gz"
      sha256 "361444e095fd1cb41dfea8d50ea4367ad4ea492693da62ef1d22d9566a62f333"

      def install
        bin.install "zitadel"
      end
    end
  end
  
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zitadel/zitadel/releases/download/v3.2.3/zitadel-linux-arm64.tar.gz"
      sha256 "0cb788648d2c05eb344653a640aa8d32df9969db69ffbe612f548a90e76cb86c"

      def install
        bin.install "zitadel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zitadel/zitadel/releases/download/v3.2.3/zitadel-linux-amd64.tar.gz"
      sha256 "64b7da65ad923182ef8d82b238f40a514ae1fbab1520bc518589e836a8b19bd8"

      def install
        bin.install "zitadel"
      end
    end
  end

  test do
    system "#{bin}/zitadel -v"
  end
end
  