# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zitadel < Formula
  desc "Open source identity solution built for the container and cloud era"
  homepage "https://zitadel.com"
  version "v2.68.1"
  license "Apache 2.0"

  depends_on "go" => :optional
  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zitadel/zitadel/releases/download/v2.68.1/zitadel-darwin-arm64.tar.gz"
      sha256 "daa24e1a6cb15eb7620633985e6562a399a0ac6995664585621f68308f68a802"

      def install
        bin.install "zitadel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zitadel/zitadel/releases/download/v2.68.1/zitadel-darwin-amd64.tar.gz"
      sha256 "8099df1b10edc35ae166f0a8fd5cf7146bdf6c5a65aec6f203bb489a1a1b4247"

      def install
        bin.install "zitadel"
      end
    end
  end
  
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zitadel/zitadel/releases/download/v2.68.1/zitadel-linux-arm64.tar.gz"
      sha256 "f4351486813da99f2d0863025c910b07aced3f5abc24e3c8e247bb8d51e738b6"

      def install
        bin.install "zitadel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zitadel/zitadel/releases/download/v2.68.1/zitadel-linux-amd64.tar.gz"
      sha256 "f63847a8d8b429f73903842358de388744cdf036e43b5825eff49d751a134b22"

      def install
        bin.install "zitadel"
      end
    end
  end

  test do
    system "#{bin}/zitadel -v"
  end
end
  