name: Update ZITADEL version

on:
  repository_dispatch:
  workflow_dispatch: 
    inputs:
      version:
        default: v2.48.1
        type: string
      runId:
        default: 8374553520
        type: number

jobs:
  print:
    runs-on: ubuntu-22.04
    steps:
      - 
        name: download sums
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          name: checksums.txt
          run-id: ${{ github.event.inputs.runId }}
          repository: zitadel/zitadel
          path: ./tmp
      - 
        name: show
        run: ls -R
      -
        name: cat
        run: cat ./tmp/checksums.txt
      - name: print
        run: |
          echo ${{ github.event }}\n  
          echo ======================================================\n
          echo ${{ github.event.client_payload }}\n
          echo ${{ github.event.client_payload.version }}\n
          echo ${{ github.event.client_payload.runId }}\n
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Formula/zitadel.rb
            .template/zitadel.rb
      - name: fill template
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          sed \
            -e "s/__VERSION__/${VERSION}/g" \
            -e "s/__DARWIN_ARM64_SUM__/$(awk '/zitadel-darwin-arm64.tar.gz/ {print $1}' ./tmp/checksums.txt)/g" \
            -e "s/__DARWIN_X86_64_SUM__/$(awk '/zitadel-darwin-amd64.tar.gz/ {print $1}' ./tmp/checksums.txt)/g" \
            -e "s/__LINUX_ARM64_SUM__/$(awk '/zitadel-linux-arm64.tar.gz/ {print $1}' ./tmp/checksums.txt)/g" \
            -e "s/__LINUX_X86_64_SUM__/$(awk '/zitadel-linux-amd64.tar.gz/ {print $1}' ./tmp/checksums.txt)/g" \
            .template/zitadel.rb